### ISSUE TITLE
MetaPackage or single pacakge

### ISSUE THREAD

**Issue by superjax** [rosflight/rosflight#3]
I'm wondering if we want to combine them all into one big ROS package.  

`rosrun rosflight rosflight_io`

`rosrun rosflight joy`

@dpkoch, What do  you think?

**Comment by dpkoch** [comment]
Here's my current plan:
 - rosflight (metapackage)
 - rosflight_msgs
 - rosflight_common
 - rosflight_io

This seems to be the way things are commonly done (gazebo, for example). I think breaking msgs out into its own package is especially a good idea so that it's a very lightweight dependency if all you to to do is view messages. Do you like that?

**Comment by dpkoch** [comment]
Closed by #5
